/* Module App */
export const APP_SET_CC_INITED = 'APP_SET_CC_INITED'
export const APP_SET_THINGS_INITED = 'APP_SET_THINGS_INITED'
export const APP_SET_THING_NAME = 'APP_SET_THING_NAME'

/* Module Auth */
export const AUTH_LOGIN_RESPONSE = 'AUTH_LOGIN_RESPONSE'

/* Module Observation */
export const OBSERVATION_FIND_RESPONSE = 'OBSERVATION_FIND_RESPONSE'

/* Module Thing */
export const THING_GET_RESPONSE = 'THING_GET_RESPONSE'
export const THING_FIND_RESPONSE = 'THING_FIND_RESPONSE'
export const THING_GET_MQTT = 'THING_GET_MQTT'
export const THING_REMOVE = 'THING_REMOVE'
